repos:
  - repo: local
    hooks:
      - id: gate-commit
        name: gate-commit
        entry: make gate-commit
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: gate-push
        name: gate-push
        entry: make gate-push
        language: system
        pass_filenames: false
        stages: [pre-push]
