[paths]
cache_dir = ".tzp/cache"
config_dir = ".tzp/config"

[cache]
extension = ".bin"
en_hash_filename = "en.hashes.bin"

[formats]
translation_ext = ".txt"
comment_prefix = "--"

[diff]
insertion_enabled_globs = ["*.txt"]
preview_context_lines = 3
